import 'package:flutter/material.dart';
import 'package:triangle_home/core/constants/enums.dart';
import 'package:triangle_home/models/room_model.dart';
import 'package:triangle_home/services/inventory_service.dart';
import 'package:triangle_home/theme/app_theme.dart';

class InventorySetupStep extends StatefulWidget {
  final String propertyId;
  final VoidCallback onComplete;

  const InventorySetupStep({
    super.key,
    required this.propertyId,
    required this.onComplete,
  });

  @override
  State<InventorySetupStep> createState() => _InventorySetupStepState();
}

class _InventorySetupStepState extends State<InventorySetupStep> {
  final InventoryService _inventoryService = InventoryService();
  bool _isLoading = false;

  final List<Map<String, dynamic>> _pendingRooms = [];

  void _addRoom() {
    showDialog(
      context: context,
      builder: (context) => _AddRoomDialog(
        onAdd: (roomData) {
          setState(() => _pendingRooms.add(roomData));
        },
      ),
    );
  }

  Future<void> _submitInventory() async {
    if (_pendingRooms.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please add at least one room')),
      );
      return;
    }

    setState(() => _isLoading = true);
    try {
      for (final roomData in _pendingRooms) {
        final room = RoomModel(
          id: '', // Generated by service
          roomNumber: roomData['number'],
          roomType: roomData['type'],
          floor: roomData['floor'],
          totalBeds: roomData['beds'].length,
          availableBeds: roomData['beds'].length,
          occupiedBeds: 0,
          baseRent: roomData['rent'],
          baseDeposit: roomData['deposit'],
          amenities: [],
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );

        await _inventoryService.createRoomWithBeds(
          propertyId: widget.propertyId,
          room: room,
          bedNumbers: List<String>.from(roomData['beds']),
        );
      }
      widget.onComplete();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Column(
        children: [
          _buildHeader(),
          Expanded(
            child: _pendingRooms.isEmpty
                ? _buildEmptyState()
                : ListView.builder(
                    padding: const EdgeInsets.all(20),
                    itemCount: _pendingRooms.length,
                    itemBuilder: (context, index) => _RoomPreviewCard(
                      data: _pendingRooms[index],
                      onDelete: () => setState(() => _pendingRooms.removeAt(index)),
                    ),
                  ),
          ),
          _buildBottomActions(),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.fromLTRB(24, 60, 24, 24),
      color: AppTheme.successColor,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Inventory Setup',
            style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold, fontFamily: 'Outfit'),
          ),
          const SizedBox(height: 8),
          Text(
            'Define rooms and beds for your property',
            style: TextStyle(color: Colors.white.withOpacity(0.8), fontSize: 14),
          ),
        ],
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.bed_rounded, size: 64, color: Colors.grey[200]),
          const SizedBox(height: 16),
          const Text('No rooms added yet', style: TextStyle(color: Colors.grey, fontWeight: FontWeight.bold)),
          const SizedBox(height: 8),
          const Text('Click "Add Room" to start building your inventory', style: TextStyle(color: Colors.grey, fontSize: 12)),
        ],
      ),
    );
  }

  Widget _buildBottomActions() {
    return Container(
      padding: const EdgeInsets.fromLTRB(24, 20, 24, 40),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 20, offset: const Offset(0, -5))],
      ),
      child: Row(
        children: [
          Expanded(
            child: OutlinedButton(
              onPressed: _addRoom,
              style: OutlinedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 16),
                side: const BorderSide(color: AppTheme.successColor),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              child: const Text('Add Room', style: TextStyle(color: AppTheme.successColor, fontWeight: FontWeight.bold)),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: ElevatedButton(
              onPressed: _isLoading ? null : _submitInventory,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.successColor,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: _isLoading
                  ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                  : const Text('Finish Setup', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
            ),
          ),
        ],
      ),
    );
  }
}

class _RoomPreviewCard extends StatelessWidget {
  final Map<String, dynamic> data;
  final VoidCallback onDelete;

  const _RoomPreviewCard({required this.data, required this.onDelete});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12)),
            child: const Icon(Icons.meeting_room_rounded, color: AppTheme.successColor),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Room ${data['number']}', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                Text('${data['type'].toString().split('.').last.toUpperCase()} • Floor ${data['floor']}', 
                  style: const TextStyle(color: Colors.grey, fontSize: 12)),
              ],
            ),
          ),
          IconButton(onPressed: onDelete, icon: const Icon(Icons.delete_outline, color: Colors.red)),
        ],
      ),
    );
  }
}

class _AddRoomDialog extends StatefulWidget {
  final Function(Map<String, dynamic>) onAdd;

  const _AddRoomDialog({required this.onAdd});

  @override
  State<_AddRoomDialog> createState() => _AddRoomDialogState();
}

class _AddRoomDialogState extends State<_AddRoomDialog> {
  final _numberController = TextEditingController();
  final _floorController = TextEditingController();
  final _rentController = TextEditingController();
  final _depositController = TextEditingController();
  RoomType _selectedType = RoomType.single;

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Room', style: TextStyle(fontWeight: FontWeight.bold)),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            _buildField('Room Number (e.g. 101)', _numberController, TextInputType.text),
            const SizedBox(height: 16),
            _buildTypeDropdown(),
            const SizedBox(height: 16),
            _buildField('Floor', _floorController, TextInputType.number),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(child: _buildField('Monthly Rent', _rentController, TextInputType.number)),
                const SizedBox(width: 12),
                Expanded(child: _buildField('Security Deposit', _depositController, TextInputType.number)),
              ],
            ),
          ],
        ),
      ),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
        ElevatedButton(
          onPressed: () {
            if (_numberController.text.isEmpty) return;
            
            // Auto-generate bed names (A, B, C...) based on type
            int bedCount = 1;
            if (_selectedType == RoomType.double) bedCount = 2;
            if (_selectedType == RoomType.triple) bedCount = 3;
            if (_selectedType == RoomType.dormitory) bedCount = 4;

            final List<String> beds = List.generate(bedCount, (i) => String.fromCharCode(65 + i));

            widget.onAdd({
              'number': _numberController.text,
              'type': _selectedType,
              'floor': int.tryParse(_floorController.text) ?? 0,
              'rent': double.tryParse(_rentController.text) ?? 0,
              'deposit': double.tryParse(_depositController.text) ?? 0,
              'beds': beds,
            });
            Navigator.pop(context);
          },
          style: ElevatedButton.styleFrom(backgroundColor: AppTheme.successColor, foregroundColor: Colors.white),
          child: const Text('Add'),
        ),
      ],
    );
  }

  Widget _buildField(String label, TextEditingController controller, TextInputType type) {
    return TextField(
      controller: controller,
      keyboardType: type,
      decoration: InputDecoration(
        labelText: label,
        filled: true,
        fillColor: Colors.grey[50],
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      ),
    );
  }

  Widget _buildTypeDropdown() {
    return DropdownButtonFormField<RoomType>(
      value: _selectedType,
      items: RoomType.values.map((t) => DropdownMenuItem(value: t, child: Text(t.name.toUpperCase()))).toList(),
      onChanged: (val) => setState(() => _selectedType = val!),
      decoration: InputDecoration(
        labelText: 'Room Type',
        filled: true,
        fillColor: Colors.grey[50],
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
      ),
    );
  }
}
