// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkrdX7tLSV-PaTDsy7I3o0mEcc1T3SLDM',
    appId: '1:318624228870:web:ecd79eaeb323d5d3ea8587',
    messagingSenderId: '318624228870',
    projectId: 'trianglehome',
    authDomain: 'trianglehome.firebaseapp.com',
    storageBucket: 'trianglehome.firebasestorage.app',
    measurementId: 'G-140T72V49Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq42OG1bSYpR9c1OFex2N0E0tOJl7FiDA',
    appId: '1:318624228870:android:199abed7f2a2285aea8587',
    messagingSenderId: '318624228870',
    projectId: 'trianglehome',
    storageBucket: 'trianglehome.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4GjBS1u7Mzng5anUqd3QYECkXNY1tESM',
    appId: '1:318624228870:ios:081b60a18e363746ea8587',
    messagingSenderId: '318624228870',
    projectId: 'trianglehome',
    storageBucket: 'trianglehome.firebasestorage.app',
    iosBundleId: 'com.example.triangleHome',
  );
}
