// Mocks generated by Mockito 5.4.4 from annotations
// in triangle_home/test/unit/hoster_stats_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:isar/isar.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:triangle_home/models/local_location.dart' as _i5;
import 'package:triangle_home/models/local_user.dart' as _i6;
import 'package:triangle_home/models/pending_action.dart' as _i7;
import 'package:triangle_home/services/isar_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIsar_0 extends _i1.SmartFake implements _i2.Isar {
  _FakeIsar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IsarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsarService extends _i1.Mock implements _i3.IsarService {
  MockIsarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Isar> get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _i4.Future<_i2.Isar>.value(_FakeIsar_0(
          this,
          Invocation.getter(#db),
        )),
      ) as _i4.Future<_i2.Isar>);

  @override
  set db(_i4.Future<_i2.Isar>? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.Isar> openDB() => (super.noSuchMethod(
        Invocation.method(
          #openDB,
          [],
        ),
        returnValue: _i4.Future<_i2.Isar>.value(_FakeIsar_0(
          this,
          Invocation.method(
            #openDB,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Isar>);

  @override
  _i4.Future<void> saveAdminCache(
    String? key,
    String? jsonData, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAdminCache,
          [
            key,
            jsonData,
          ],
          {#ttl: ttl},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAdminCache(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getAdminCache,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearAdminCache(String? key) => (super.noSuchMethod(
        Invocation.method(
          #clearAdminCache,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanStaleCache() => (super.noSuchMethod(
        Invocation.method(
          #cleanStaleCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveDraft(
    String? type,
    String? id,
    String? jsonData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [
            type,
            id,
            jsonData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getDraft(
    String? type,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDraft,
          [
            type,
            id,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearDraft(
    String? type,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearDraft,
          [
            type,
            id,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveMaintenanceDraft(
    String? residentId,
    String? jsonData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMaintenanceDraft,
          [
            residentId,
            jsonData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getMaintenanceDraft(String? residentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMaintenanceDraft,
          [residentId],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearMaintenanceDraft(String? residentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearMaintenanceDraft,
          [residentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> savePropertyDraft(
    String? hosterId,
    String? jsonData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePropertyDraft,
          [
            hosterId,
            jsonData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getPropertyDraft(String? hosterId) => (super.noSuchMethod(
        Invocation.method(
          #getPropertyDraft,
          [hosterId],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearPropertyDraft(String? hosterId) => (super.noSuchMethod(
        Invocation.method(
          #clearPropertyDraft,
          [hosterId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveMajorCities(List<String>? cities) => (super.noSuchMethod(
        Invocation.method(
          #saveMajorCities,
          [cities],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getCachedMajorCities() => (super.noSuchMethod(
        Invocation.method(
          #getCachedMajorCities,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> saveLocationPreference({
    String? selected,
    String? detected,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocationPreference,
          [],
          {
            #selected: selected,
            #detected: detected,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserLocationPreference?> getLocationPreference() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationPreference,
          [],
        ),
        returnValue: _i4.Future<_i5.UserLocationPreference?>.value(),
      ) as _i4.Future<_i5.UserLocationPreference?>);

  @override
  _i4.Future<void> saveLocalUser(_i6.LocalUser? user) => (super.noSuchMethod(
        Invocation.method(
          #saveLocalUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.LocalUser?> getLocalUser(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #getLocalUser,
          [uid],
        ),
        returnValue: _i4.Future<_i6.LocalUser?>.value(),
      ) as _i4.Future<_i6.LocalUser?>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearHosterCache(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #clearHosterCache,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setUserIntent(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setUserIntent,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getUserIntent() => (super.noSuchMethod(
        Invocation.method(
          #getUserIntent,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> clearUserIntent() => (super.noSuchMethod(
        Invocation.method(
          #clearUserIntent,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enqueueAction(
    String? actionId,
    String? type,
    String? payload,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueAction,
          [
            actionId,
            type,
            payload,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.PendingAction>> dequeueActions() => (super.noSuchMethod(
        Invocation.method(
          #dequeueActions,
          [],
        ),
        returnValue:
            _i4.Future<List<_i7.PendingAction>>.value(<_i7.PendingAction>[]),
      ) as _i4.Future<List<_i7.PendingAction>>);

  @override
  _i4.Future<void> removeAction(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeAction,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> incrementActionRetry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #incrementActionRetry,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSearchResult(
    String? queryKey,
    List<String>? propertyIds, {
    Duration? ttl = const Duration(minutes: 5),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSearchResult,
          [
            queryKey,
            propertyIds,
          ],
          {#ttl: ttl},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>?> getSearchResult(String? queryKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchResult,
          [queryKey],
        ),
        returnValue: _i4.Future<List<String>?>.value(),
      ) as _i4.Future<List<String>?>);
}
